### ISSUE TITLE
Copyrights & Licenses?

### ISSUE THREAD

**Issue by graphefruit** [obiwan007/despresso#106]
This repo looks like using codes from 
https://github.com/Mimoja/flupresso#readme

The scale_service.dart is like 99.95% identical:

https://github.com/obiwan007/despresso/commit/e8ae28838b0f2e54946eb5e6fc217fcf695f5a68#diff-979a02938d904eb101c27a1fd79ff7cd2a3741e2840fd8ce65761e76464c690b
vs
https://github.com/Mimoja/flupresso/blob/master/lib/model/services/ble/scale_service.dart

After the repo of Mimoja/flupresso has no licence:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

`
However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The [Open Source Guide](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) provides additional guidance on choosing the correct license for your project.
`

**Comment by Mimoja** [comment]
I am very much okay relicensing my original code GPLv3, if credit is given as requested in #105 which i would prefer to see :)

Given that any progress is better than licensing frustration I think we should just get this to a good solution asap :)

**Comment by obiwan007** [comment]
No Problem to give anybody credit if deserved.
Not sure where exactly though.

**Comment by obiwan007** [comment]
Just created a credits page. Feel free at add things there - I am probably still missing people there.

**Comment by graphefruit** [comment]
After it was deeper discussed in the other ticket, I'm going to close this one here!
Thanks!
